- name: frontend
  color: '1D76DB'
  description: 'Vue UI tasks'
- name: backend
  color: '5319E7'
  description: 'FastAPI backend and APIs'
- name: auth
  color: 'FBCA04'
  description: 'User and document-level authorization'
- name: vector-db
  color: '0E8A16'
  description: 'Qdrant or vector store related'
- name: docs
  color: '0052CC'
  description: 'Documentation and design notes'
- name: enhancement
  color: 'BFDADC'
  description: 'Feature or improvement'
- name: bug
  color: 'D73A4A'
  description: 'Bugs and issues'
