"""add error_reports table

Revision ID: 2f22a638a909
Revises: dbc6269d79ba
Create Date: 2025-12-05 19:15:09.614741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f22a638a909'
down_revision: Union[str, None] = 'dbc6269d79ba'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('LLM_ERROR', 'RETRIEVAL_ERROR', 'VALIDATION_ERROR', 'PERFORMANCE', 'UI_UX', 'PERMISSIONS', 'DATA_ACCURACY', 'SYSTEM_ERROR', 'OTHER', name='errorreportcategory'), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('request_context', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'ACKNOWLEDGED', 'RESOLVED', 'DUPLICATE', 'NOT_REPRODUCIBLE', 'WONT_FIX', name='errorreportstatus'), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_reports_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_reports_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index('ix_error_reports_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_reports_status'), ['status'], unique=False)
        batch_op.create_index('ix_error_reports_status_category', ['status', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_reports_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_reports_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_error_reports_user_status', ['user_id', 'status'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_notifications_type_created'))
        batch_op.drop_index(batch_op.f('idx_notifications_user_unread'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_related_file_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_updated_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_password_reset_tokens_created_at'))
        batch_op.drop_index(batch_op.f('idx_password_reset_tokens_email'))
        batch_op.drop_index(batch_op.f('idx_password_reset_tokens_expires_at'))
        batch_op.drop_index(batch_op.f('idx_password_reset_tokens_is_used'))
        batch_op.drop_index(batch_op.f('idx_password_reset_tokens_token'))
        batch_op.drop_index(batch_op.f('idx_password_reset_tokens_updated_at'))
        batch_op.drop_index(batch_op.f('idx_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('idx_token_email_valid'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_jobs_reference'))
        batch_op.drop_index(batch_op.f('ix_jobs_reference_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_reference_type'))
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_status_type'))

    op.drop_table('jobs')
    with op.batch_alter_table('application_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_application_settings_key'), type_='unique')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_last_message_at'), ['last_message_at'], unique=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_department_code'))
        batch_op.drop_index(batch_op.f('ix_department_created_at'))
        batch_op.drop_index(batch_op.f('ix_department_is_active'))
        batch_op.drop_index(batch_op.f('ix_department_name'))
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_departments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_name'), ['name'], unique=False)

    with op.batch_alter_table('file_uploads', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'PROCESSING', 'PROCESSED', 'FAILED', 'DELETED', name='filestatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.drop_constraint(batch_op.f('file_uploads_upload_token_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_file_upload_created_at'))
        batch_op.drop_index(batch_op.f('ix_file_upload_department_id'))
        batch_op.drop_index(batch_op.f('ix_file_upload_file_hash'))
        batch_op.drop_index(batch_op.f('ix_file_upload_file_name'))
        batch_op.drop_index(batch_op.f('ix_file_upload_file_type'))
        batch_op.drop_index(batch_op.f('ix_file_upload_is_department_only'))
        batch_op.drop_index(batch_op.f('ix_file_upload_is_processed'))
        batch_op.drop_index(batch_op.f('ix_file_upload_security_level'))
        batch_op.drop_index(batch_op.f('ix_file_upload_status'))
        batch_op.drop_index(batch_op.f('ix_file_upload_upload_token'))
        batch_op.create_index('idx_file_upload_is_processed', ['is_processed'], unique=False)
        batch_op.create_index('idx_file_upload_security_level', ['security_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_uploads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_uploads_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_uploads_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_uploads_file_name'), ['file_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_uploads_file_type'), ['file_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_uploads_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_uploads_is_department_only'), ['is_department_only'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_uploads_is_processed'), ['is_processed'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_uploads_retention_until'), ['retention_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_uploads_security_level'), ['security_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_uploads_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_uploads_upload_token'), ['upload_token'], unique=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_resource_action'))
        batch_op.drop_constraint(batch_op.f('uq_permissions_code'), type_='unique')
        batch_op.create_index('idx_permission_resource_action', ['resource', 'action'], unique=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_roles_name'), type_='unique')

    with op.batch_alter_table('user_invitations', schema=None) as batch_op:
        batch_op.alter_column('org_level_permission',
               existing_type=sa.INTEGER(),
               comment='Organization-wide clearance level (1-4)',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('department_level_permission',
               existing_type=sa.INTEGER(),
               comment='Department-specific clearance level (1-4)',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_user_invitations_department_id'))
        batch_op.drop_index(batch_op.f('ix_invitation_email'))
        batch_op.drop_index(batch_op.f('ix_invitation_expires_at'))
        batch_op.drop_index(batch_op.f('ix_invitation_status'))
        batch_op.drop_index(batch_op.f('ix_invitation_token'))
        batch_op.drop_constraint(batch_op.f('uq_user_invitations_token'), type_='unique')
        batch_op.create_index('idx_invitation_department', ['department_id'], unique=False)
        batch_op.create_index('idx_invitation_email', ['email'], unique=False)
        batch_op.create_index('idx_invitation_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('idx_invitation_status', ['status'], unique=False)
        batch_op.create_index('idx_invitation_token', ['token'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_invitations_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_invitations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_invitations_token'), ['token'], unique=True)

    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_permissions_dept_level'))
        batch_op.drop_index(batch_op.f('ix_user_permissions_org_level'))
        batch_op.drop_constraint(batch_op.f('user_permissions_user_id_key'), type_='unique')
        batch_op.create_index('idx_user_permission_dept_level', ['department_id', 'department_level_permission'], unique=False)
        batch_op.create_index('idx_user_permission_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_user_permission_org_level', ['org_level_permission'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_permissions_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profile_user_id'))
        batch_op.drop_constraint(batch_op.f('uq_user_profiles_user_id'), type_='unique')
        batch_op.create_index('idx_user_profile_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))
        batch_op.drop_index('idx_user_profile_user_id')
        batch_op.create_unique_constraint(batch_op.f('uq_user_profiles_user_id'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_user_profile_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_permissions_created_at'))
        batch_op.drop_index('idx_user_permission_org_level')
        batch_op.drop_index('idx_user_permission_is_active')
        batch_op.drop_index('idx_user_permission_dept_level')
        batch_op.create_unique_constraint(batch_op.f('user_permissions_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_user_permissions_org_level'), ['org_level_permission'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_permissions_dept_level'), ['department_id', 'department_level_permission'], unique=False)

    with op.batch_alter_table('user_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_invitations_token'))
        batch_op.drop_index(batch_op.f('ix_user_invitations_status'))
        batch_op.drop_index(batch_op.f('ix_user_invitations_expires_at'))
        batch_op.drop_index(batch_op.f('ix_user_invitations_email'))
        batch_op.drop_index('idx_invitation_token')
        batch_op.drop_index('idx_invitation_status')
        batch_op.drop_index('idx_invitation_expires_at')
        batch_op.drop_index('idx_invitation_email')
        batch_op.drop_index('idx_invitation_department')
        batch_op.create_unique_constraint(batch_op.f('uq_user_invitations_token'), ['token'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_invitation_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_invitation_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitation_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitation_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_invitations_department_id'), ['department_id'], unique=False)
        batch_op.alter_column('department_level_permission',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Department-specific clearance level (1-4)',
               existing_nullable=True)
        batch_op.alter_column('org_level_permission',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Organization-wide clearance level (1-4)',
               existing_nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_roles_name'), ['name'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index('idx_permission_resource_action')
        batch_op.create_unique_constraint(batch_op.f('uq_permissions_code'), ['code'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_permissions_resource_action'), ['resource', 'action'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_id'))

    with op.batch_alter_table('file_uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_uploads_upload_token'))
        batch_op.drop_index(batch_op.f('ix_file_uploads_status'))
        batch_op.drop_index(batch_op.f('ix_file_uploads_security_level'))
        batch_op.drop_index(batch_op.f('ix_file_uploads_retention_until'))
        batch_op.drop_index(batch_op.f('ix_file_uploads_is_processed'))
        batch_op.drop_index(batch_op.f('ix_file_uploads_is_department_only'))
        batch_op.drop_index(batch_op.f('ix_file_uploads_is_archived'))
        batch_op.drop_index(batch_op.f('ix_file_uploads_file_type'))
        batch_op.drop_index(batch_op.f('ix_file_uploads_file_name'))
        batch_op.drop_index(batch_op.f('ix_file_uploads_file_hash'))
        batch_op.drop_index(batch_op.f('ix_file_uploads_department_id'))
        batch_op.drop_index(batch_op.f('ix_file_uploads_created_at'))
        batch_op.drop_index('idx_file_upload_security_level')
        batch_op.drop_index('idx_file_upload_is_processed')
        batch_op.create_index(batch_op.f('ix_file_upload_upload_token'), ['upload_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_file_upload_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_upload_security_level'), ['security_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_upload_is_processed'), ['is_processed'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_upload_is_department_only'), ['is_department_only'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_upload_file_type'), ['file_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_upload_file_name'), ['file_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_upload_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_upload_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_upload_created_at'), ['created_at'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('file_uploads_upload_token_key'), ['upload_token'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'PROCESSING', 'PROCESSED', 'FAILED', 'DELETED', name='filestatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_name'))
        batch_op.drop_index(batch_op.f('ix_departments_is_active'))
        batch_op.drop_index(batch_op.f('ix_departments_created_at'))
        batch_op.drop_index(batch_op.f('ix_departments_code'))
        batch_op.create_index(batch_op.f('ix_department_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_code'), ['code'], unique=False)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_last_message_at'))
        batch_op.drop_index(batch_op.f('ix_conversations_id'))

    with op.batch_alter_table('application_settings', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_application_settings_key'), ['key'], postgresql_nulls_not_distinct=False)

    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reference_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('max_retries', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_status_type'), ['status', 'job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_reference_type'), ['reference_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_reference'), ['reference_type', 'reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_job_type'), ['job_type'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('password_reset_tokens_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('password_reset_tokens_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_token_email_valid'), ['token', 'email', 'is_used', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_password_reset_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_password_reset_tokens_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_password_reset_tokens_token'), ['token'], unique=False)
        batch_op.create_index(batch_op.f('idx_password_reset_tokens_is_used'), ['is_used'], unique=False)
        batch_op.create_index(batch_op.f('idx_password_reset_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_password_reset_tokens_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_password_reset_tokens_created_at'), ['created_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('related_file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notification_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['related_file_id'], ['file_uploads.id'], name=op.f('notifications_related_file_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_related_file_id'), ['related_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_notifications_user_unread'), ['user_id', 'is_read'], unique=False)
        batch_op.create_index(batch_op.f('idx_notifications_type_created'), ['notification_type', 'created_at'], unique=False)

    with op.batch_alter_table('error_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_error_reports_user_status')
        batch_op.drop_index(batch_op.f('ix_error_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_error_reports_title'))
        batch_op.drop_index('ix_error_reports_status_category')
        batch_op.drop_index(batch_op.f('ix_error_reports_status'))
        batch_op.drop_index('ix_error_reports_created_at')
        batch_op.drop_index(batch_op.f('ix_error_reports_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_error_reports_category'))

    op.drop_table('error_reports')
    # ### end Alembic commands ###
