"""Add approval workflow to permission_overrides

Revision ID: dbc6269d79ba
Revises: 019
Create Date: 2025-12-04 18:44:13.534606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dbc6269d79ba'
down_revision: Union[str, None] = '019'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_password_reset_tokens_created_at'), table_name='password_reset_tokens')
    op.drop_index(op.f('idx_password_reset_tokens_email'), table_name='password_reset_tokens')
    op.drop_index(op.f('idx_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.drop_index(op.f('idx_password_reset_tokens_is_used'), table_name='password_reset_tokens')
    op.drop_index(op.f('idx_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('idx_password_reset_tokens_updated_at'), table_name='password_reset_tokens')
    op.drop_index(op.f('idx_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('idx_token_email_valid'), table_name='password_reset_tokens')
    op.drop_index(op.f('token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('idx_notifications_type_created'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user_unread'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_file_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_updated_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_reference'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_reference_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_reference_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status_type'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('uq_application_settings_key'), table_name='application_settings')
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.alter_column('departments', 'code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_department_code'), table_name='departments')
    op.drop_index(op.f('ix_department_created_at'), table_name='departments')
    op.drop_index(op.f('ix_department_is_active'), table_name='departments')
    op.drop_index(op.f('ix_department_name'), table_name='departments')
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_created_at'), 'departments', ['created_at'], unique=False)
    op.create_index(op.f('ix_departments_is_active'), 'departments', ['is_active'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=False)
    op.alter_column('file_uploads', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'PROCESSING', 'PROCESSED', 'FAILED', 'DELETED', name='filestatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.drop_index(op.f('ix_file_upload_created_at'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_upload_department_id'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_upload_file_hash'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_upload_file_name'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_upload_file_type'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_upload_is_department_only'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_upload_is_processed'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_upload_security_level'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_upload_status'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_upload_upload_token'), table_name='file_uploads')
    op.drop_index(op.f('upload_token'), table_name='file_uploads')
    op.create_index('idx_file_upload_is_processed', 'file_uploads', ['is_processed'], unique=False)
    op.create_index('idx_file_upload_security_level', 'file_uploads', ['security_level'], unique=False)
    op.create_index(op.f('ix_file_uploads_created_at'), 'file_uploads', ['created_at'], unique=False)
    op.create_index(op.f('ix_file_uploads_department_id'), 'file_uploads', ['department_id'], unique=False)
    op.create_index(op.f('ix_file_uploads_file_hash'), 'file_uploads', ['file_hash'], unique=False)
    op.create_index(op.f('ix_file_uploads_file_name'), 'file_uploads', ['file_name'], unique=False)
    op.create_index(op.f('ix_file_uploads_file_type'), 'file_uploads', ['file_type'], unique=False)
    op.create_index(op.f('ix_file_uploads_is_archived'), 'file_uploads', ['is_archived'], unique=False)
    op.create_index(op.f('ix_file_uploads_is_department_only'), 'file_uploads', ['is_department_only'], unique=False)
    op.create_index(op.f('ix_file_uploads_is_processed'), 'file_uploads', ['is_processed'], unique=False)
    op.create_index(op.f('ix_file_uploads_retention_until'), 'file_uploads', ['retention_until'], unique=False)
    op.create_index(op.f('ix_file_uploads_security_level'), 'file_uploads', ['security_level'], unique=False)
    op.create_index(op.f('ix_file_uploads_status'), 'file_uploads', ['status'], unique=False)
    op.create_index(op.f('ix_file_uploads_upload_token'), 'file_uploads', ['upload_token'], unique=True)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.add_column('permission_overrides', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('permission_overrides', sa.Column('approver_id', sa.Integer(), nullable=True))
    op.add_column('permission_overrides', sa.Column('approval_notes', sa.Text(), nullable=True))
    op.add_column('permission_overrides', sa.Column('decided_at', sa.DateTime(), nullable=True))
    op.add_column('permission_overrides', sa.Column('trigger_query', sa.Text(), nullable=True))
    op.add_column('permission_overrides', sa.Column('trigger_file_id', sa.Integer(), nullable=True))
    op.add_column('permission_overrides', sa.Column('auto_escalated', sa.Boolean(), nullable=False))
    op.add_column('permission_overrides', sa.Column('escalated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_permission_overrides_status'), 'permission_overrides', ['status'], unique=False)
    op.create_index('ix_permission_overrides_status_created', 'permission_overrides', ['status', 'created_at'], unique=False)
    op.create_index('ix_permission_overrides_user_status', 'permission_overrides', ['user_id', 'status'], unique=False)
    op.create_foreign_key(None, 'permission_overrides', 'users', ['approver_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_permissions_resource_action'), table_name='permissions')
    op.drop_index(op.f('uq_permissions_code'), table_name='permissions')
    op.create_index('idx_permission_resource_action', 'permissions', ['resource', 'action'], unique=False)
    op.drop_index(op.f('uq_roles_name'), table_name='roles')
    op.add_column('user_invitations', sa.Column('org_level_permission', sa.Integer(), nullable=False, comment='Organization-wide clearance level (1-4)'))
    op.add_column('user_invitations', sa.Column('department_level_permission', sa.Integer(), nullable=True, comment='Department-specific clearance level (1-4)'))
    op.alter_column('user_invitations', 'department_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Department to assign user to during onboarding',
               existing_nullable=True)
    op.alter_column('user_invitations', 'is_manager',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Whether to make user a manager of assigned department',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('idx_user_invitations_department_id'), table_name='user_invitations')
    op.drop_index(op.f('ix_invitation_email'), table_name='user_invitations')
    op.drop_index(op.f('ix_invitation_expires_at'), table_name='user_invitations')
    op.drop_index(op.f('ix_invitation_status'), table_name='user_invitations')
    op.drop_index(op.f('ix_invitation_token'), table_name='user_invitations')
    op.drop_index(op.f('uq_user_invitations_token'), table_name='user_invitations')
    op.create_index('idx_invitation_department', 'user_invitations', ['department_id'], unique=False)
    op.create_index('idx_invitation_email', 'user_invitations', ['email'], unique=False)
    op.create_index('idx_invitation_expires_at', 'user_invitations', ['expires_at'], unique=False)
    op.create_index('idx_invitation_status', 'user_invitations', ['status'], unique=False)
    op.create_index('idx_invitation_token', 'user_invitations', ['token'], unique=False)
    op.create_index(op.f('ix_user_invitations_email'), 'user_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_user_invitations_expires_at'), 'user_invitations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_invitations_status'), 'user_invitations', ['status'], unique=False)
    op.create_index(op.f('ix_user_invitations_token'), 'user_invitations', ['token'], unique=True)
    op.drop_index(op.f('idx_user_permissions_dept_level'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_org_level'), table_name='user_permissions')
    op.drop_index(op.f('user_id'), table_name='user_permissions')
    op.create_index('idx_user_permission_dept_level', 'user_permissions', ['department_id', 'department_level_permission'], unique=False)
    op.create_index('idx_user_permission_is_active', 'user_permissions', ['is_active'], unique=False)
    op.create_index('idx_user_permission_org_level', 'user_permissions', ['org_level_permission'], unique=False)
    op.create_index(op.f('ix_user_permissions_created_at'), 'user_permissions', ['created_at'], unique=False)
    op.drop_index(op.f('ix_user_profile_user_id'), table_name='user_profiles')
    op.drop_index(op.f('uq_user_profiles_user_id'), table_name='user_profiles')
    op.create_index('idx_user_profile_user_id', 'user_profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('uq_users_email'), table_name='users')
    op.drop_index(op.f('uq_users_username'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('uq_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index('idx_user_profile_user_id', table_name='user_profiles')
    op.create_index(op.f('uq_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_profile_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_permissions_created_at'), table_name='user_permissions')
    op.drop_index('idx_user_permission_org_level', table_name='user_permissions')
    op.drop_index('idx_user_permission_is_active', table_name='user_permissions')
    op.drop_index('idx_user_permission_dept_level', table_name='user_permissions')
    op.create_index(op.f('user_id'), 'user_permissions', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_permissions_org_level'), 'user_permissions', ['org_level_permission'], unique=False)
    op.create_index(op.f('idx_user_permissions_dept_level'), 'user_permissions', ['department_id', 'department_level_permission'], unique=False)
    op.drop_index(op.f('ix_user_invitations_token'), table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_status'), table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_expires_at'), table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_email'), table_name='user_invitations')
    op.drop_index('idx_invitation_token', table_name='user_invitations')
    op.drop_index('idx_invitation_status', table_name='user_invitations')
    op.drop_index('idx_invitation_expires_at', table_name='user_invitations')
    op.drop_index('idx_invitation_email', table_name='user_invitations')
    op.drop_index('idx_invitation_department', table_name='user_invitations')
    op.create_index(op.f('uq_user_invitations_token'), 'user_invitations', ['token'], unique=True)
    op.create_index(op.f('ix_invitation_token'), 'user_invitations', ['token'], unique=True)
    op.create_index(op.f('ix_invitation_status'), 'user_invitations', ['status'], unique=False)
    op.create_index(op.f('ix_invitation_expires_at'), 'user_invitations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_invitation_email'), 'user_invitations', ['email'], unique=False)
    op.create_index(op.f('idx_user_invitations_department_id'), 'user_invitations', ['department_id'], unique=False)
    op.alter_column('user_invitations', 'is_manager',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Whether to make user a manager of assigned department',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user_invitations', 'department_id',
               existing_type=mysql.INTEGER(),
               comment='Department to assign user to during onboarding',
               existing_nullable=True)
    op.drop_column('user_invitations', 'department_level_permission')
    op.drop_column('user_invitations', 'org_level_permission')
    op.create_index(op.f('uq_roles_name'), 'roles', ['name'], unique=True)
    op.drop_index('idx_permission_resource_action', table_name='permissions')
    op.create_index(op.f('uq_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_resource_action'), 'permissions', ['resource', 'action'], unique=False)
    op.drop_constraint(None, 'permission_overrides', type_='foreignkey')
    op.drop_index('ix_permission_overrides_user_status', table_name='permission_overrides')
    op.drop_index('ix_permission_overrides_status_created', table_name='permission_overrides')
    op.drop_index(op.f('ix_permission_overrides_status'), table_name='permission_overrides')
    op.drop_column('permission_overrides', 'escalated_at')
    op.drop_column('permission_overrides', 'auto_escalated')
    op.drop_column('permission_overrides', 'trigger_file_id')
    op.drop_column('permission_overrides', 'trigger_query')
    op.drop_column('permission_overrides', 'decided_at')
    op.drop_column('permission_overrides', 'approval_notes')
    op.drop_column('permission_overrides', 'approver_id')
    op.drop_column('permission_overrides', 'status')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_file_uploads_upload_token'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_status'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_security_level'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_retention_until'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_is_processed'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_is_department_only'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_is_archived'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_file_type'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_file_name'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_file_hash'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_department_id'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_created_at'), table_name='file_uploads')
    op.drop_index('idx_file_upload_security_level', table_name='file_uploads')
    op.drop_index('idx_file_upload_is_processed', table_name='file_uploads')
    op.create_index(op.f('upload_token'), 'file_uploads', ['upload_token'], unique=True)
    op.create_index(op.f('ix_file_upload_upload_token'), 'file_uploads', ['upload_token'], unique=True)
    op.create_index(op.f('ix_file_upload_status'), 'file_uploads', ['status'], unique=False)
    op.create_index(op.f('ix_file_upload_security_level'), 'file_uploads', ['security_level'], unique=False)
    op.create_index(op.f('ix_file_upload_is_processed'), 'file_uploads', ['is_processed'], unique=False)
    op.create_index(op.f('ix_file_upload_is_department_only'), 'file_uploads', ['is_department_only'], unique=False)
    op.create_index(op.f('ix_file_upload_file_type'), 'file_uploads', ['file_type'], unique=False)
    op.create_index(op.f('ix_file_upload_file_name'), 'file_uploads', ['file_name'], unique=False)
    op.create_index(op.f('ix_file_upload_file_hash'), 'file_uploads', ['file_hash'], unique=False)
    op.create_index(op.f('ix_file_upload_department_id'), 'file_uploads', ['department_id'], unique=False)
    op.create_index(op.f('ix_file_upload_created_at'), 'file_uploads', ['created_at'], unique=False)
    op.alter_column('file_uploads', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'PROCESSING', 'PROCESSED', 'FAILED', 'DELETED', name='filestatus', native_enum=False),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_is_active'), table_name='departments')
    op.drop_index(op.f('ix_departments_created_at'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.create_index(op.f('ix_department_name'), 'departments', ['name'], unique=False)
    op.create_index(op.f('ix_department_is_active'), 'departments', ['is_active'], unique=False)
    op.create_index(op.f('ix_department_created_at'), 'departments', ['created_at'], unique=False)
    op.create_index(op.f('ix_department_code'), 'departments', ['code'], unique=False)
    op.alter_column('departments', 'code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.create_index(op.f('uq_application_settings_key'), 'application_settings', ['key'], unique=True)
    op.create_table('jobs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('reference_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reference_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('payload', mysql.TEXT(), nullable=True),
    sa.Column('result', mysql.TEXT(), nullable=True),
    sa.Column('error', mysql.TEXT(), nullable=True),
    sa.Column('retry_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('max_retries', mysql.INTEGER(), server_default=sa.text("'3'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_jobs_status_type'), 'jobs', ['status', 'job_type'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_reference_type'), 'jobs', ['reference_type'], unique=False)
    op.create_index(op.f('ix_jobs_reference_id'), 'jobs', ['reference_id'], unique=False)
    op.create_index(op.f('ix_jobs_reference'), 'jobs', ['reference_type', 'reference_id'], unique=False)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_table('notifications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('related_file_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notification_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('read_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['related_file_id'], ['file_uploads.id'], name=op.f('notifications_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_updated_at'), 'notifications', ['updated_at'], unique=False)
    op.create_index(op.f('ix_notifications_related_file_id'), 'notifications', ['related_file_id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('idx_notifications_user_unread'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('idx_notifications_type_created'), 'notifications', ['notification_type', 'created_at'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('is_used', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('used_at', mysql.DATETIME(), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('password_reset_tokens_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('idx_token_email_valid'), 'password_reset_tokens', ['token', 'email', 'is_used', 'expires_at'], unique=False)
    op.create_index(op.f('idx_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_password_reset_tokens_updated_at'), 'password_reset_tokens', ['updated_at'], unique=False)
    op.create_index(op.f('idx_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=False)
    op.create_index(op.f('idx_password_reset_tokens_is_used'), 'password_reset_tokens', ['is_used'], unique=False)
    op.create_index(op.f('idx_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('idx_password_reset_tokens_email'), 'password_reset_tokens', ['email'], unique=False)
    op.create_index(op.f('idx_password_reset_tokens_created_at'), 'password_reset_tokens', ['created_at'], unique=False)
    # ### end Alembic commands ###
